/**
 * Dopt Users API
 * The Dopt Users API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BadRequestErrorResponseBody from './model/BadRequestErrorResponseBody';
import BadRequestErrorResponseBodyCode from './model/BadRequestErrorResponseBodyCode';
import IdentifyBulkRequestBodyInner from './model/IdentifyBulkRequestBodyInner';
import IdentifyBulkResponseBody from './model/IdentifyBulkResponseBody';
import IdentifyRequestParams from './model/IdentifyRequestParams';
import IdentifySegmentRequestBody from './model/IdentifySegmentRequestBody';
import IdentifySegmentResponseBody from './model/IdentifySegmentResponseBody';
import InternalServerErrorResponseBody from './model/InternalServerErrorResponseBody';
import InternalServerErrorResponseBodyCode from './model/InternalServerErrorResponseBodyCode';
import NotFoundErrorResponseBody from './model/NotFoundErrorResponseBody';
import NotFoundErrorResponseBodyCode from './model/NotFoundErrorResponseBodyCode';
import UnauthorizedErrorResponseBody from './model/UnauthorizedErrorResponseBody';
import UnauthorizedErrorResponseBodyCode from './model/UnauthorizedErrorResponseBodyCode';
import IdentifyApi from './api/IdentifyApi';


/**
* The Dopt Users API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DoptUsersApi = require('index'); // See note below*.
* var xxxSvc = new DoptUsersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DoptUsersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DoptUsersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DoptUsersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BadRequestErrorResponseBody model constructor.
     * @property {module:model/BadRequestErrorResponseBody}
     */
    BadRequestErrorResponseBody,

    /**
     * The BadRequestErrorResponseBodyCode model constructor.
     * @property {module:model/BadRequestErrorResponseBodyCode}
     */
    BadRequestErrorResponseBodyCode,

    /**
     * The IdentifyBulkRequestBodyInner model constructor.
     * @property {module:model/IdentifyBulkRequestBodyInner}
     */
    IdentifyBulkRequestBodyInner,

    /**
     * The IdentifyBulkResponseBody model constructor.
     * @property {module:model/IdentifyBulkResponseBody}
     */
    IdentifyBulkResponseBody,

    /**
     * The IdentifyRequestParams model constructor.
     * @property {module:model/IdentifyRequestParams}
     */
    IdentifyRequestParams,

    /**
     * The IdentifySegmentRequestBody model constructor.
     * @property {module:model/IdentifySegmentRequestBody}
     */
    IdentifySegmentRequestBody,

    /**
     * The IdentifySegmentResponseBody model constructor.
     * @property {module:model/IdentifySegmentResponseBody}
     */
    IdentifySegmentResponseBody,

    /**
     * The InternalServerErrorResponseBody model constructor.
     * @property {module:model/InternalServerErrorResponseBody}
     */
    InternalServerErrorResponseBody,

    /**
     * The InternalServerErrorResponseBodyCode model constructor.
     * @property {module:model/InternalServerErrorResponseBodyCode}
     */
    InternalServerErrorResponseBodyCode,

    /**
     * The NotFoundErrorResponseBody model constructor.
     * @property {module:model/NotFoundErrorResponseBody}
     */
    NotFoundErrorResponseBody,

    /**
     * The NotFoundErrorResponseBodyCode model constructor.
     * @property {module:model/NotFoundErrorResponseBodyCode}
     */
    NotFoundErrorResponseBodyCode,

    /**
     * The UnauthorizedErrorResponseBody model constructor.
     * @property {module:model/UnauthorizedErrorResponseBody}
     */
    UnauthorizedErrorResponseBody,

    /**
     * The UnauthorizedErrorResponseBodyCode model constructor.
     * @property {module:model/UnauthorizedErrorResponseBodyCode}
     */
    UnauthorizedErrorResponseBodyCode,

    /**
    * The IdentifyApi service constructor.
    * @property {module:api/IdentifyApi}
    */
    IdentifyApi
};
