/**
 * Dopt Users API
 * The Dopt Users API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BadRequestErrorResponseBodyCode from './BadRequestErrorResponseBodyCode';

/**
 * The BadRequestErrorResponseBody model module.
 * @module model/BadRequestErrorResponseBody
 * @version 0.0.0
 */
class BadRequestErrorResponseBody {
    /**
     * Constructs a new <code>BadRequestErrorResponseBody</code>.
     * @alias module:model/BadRequestErrorResponseBody
     * @param code {module:model/BadRequestErrorResponseBodyCode} 
     * @param details {String} 
     */
    constructor(code, details) { 
        
        BadRequestErrorResponseBody.initialize(this, code, details);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, details) { 
        obj['code'] = code;
        obj['details'] = details;
    }

    /**
     * Constructs a <code>BadRequestErrorResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BadRequestErrorResponseBody} obj Optional instance to populate.
     * @return {module:model/BadRequestErrorResponseBody} The populated <code>BadRequestErrorResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BadRequestErrorResponseBody();

            if (data.hasOwnProperty('code')) {
                obj['code'] = BadRequestErrorResponseBodyCode.constructFromObject(data['code']);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BadRequestErrorResponseBodyCode} code
 */
BadRequestErrorResponseBody.prototype['code'] = undefined;

/**
 * @member {String} details
 */
BadRequestErrorResponseBody.prototype['details'] = undefined;






export default BadRequestErrorResponseBody;

