/**
 * Dopt Users API
 * The Dopt Users API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentifyBulkRequestBodyInner model module.
 * @module model/IdentifyBulkRequestBodyInner
 * @version 0.0.0
 */
class IdentifyBulkRequestBodyInner {
    /**
     * Constructs a new <code>IdentifyBulkRequestBodyInner</code>.
     * @alias module:model/IdentifyBulkRequestBodyInner
     * @extends Object
     * @param doptIdentifier {String} 
     */
    constructor(doptIdentifier) { 
        
        IdentifyBulkRequestBodyInner.initialize(this, doptIdentifier);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, doptIdentifier) { 
        obj['__dopt_identifier'] = doptIdentifier;
    }

    /**
     * Constructs a <code>IdentifyBulkRequestBodyInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentifyBulkRequestBodyInner} obj Optional instance to populate.
     * @return {module:model/IdentifyBulkRequestBodyInner} The populated <code>IdentifyBulkRequestBodyInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentifyBulkRequestBodyInner();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('__dopt_identifier')) {
                obj['__dopt_identifier'] = ApiClient.convertToType(data['__dopt_identifier'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} __dopt_identifier
 */
IdentifyBulkRequestBodyInner.prototype['__dopt_identifier'] = undefined;






export default IdentifyBulkRequestBodyInner;

