/**
 * Dopt Users API
 * The Dopt Users API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentifyRequestParams model module.
 * @module model/IdentifyRequestParams
 * @version 0.0.0
 */
class IdentifyRequestParams {
    /**
     * Constructs a new <code>IdentifyRequestParams</code>.
     * @alias module:model/IdentifyRequestParams
     * @param identifier {String} 
     */
    constructor(identifier) { 
        
        IdentifyRequestParams.initialize(this, identifier);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier) { 
        obj['identifier'] = identifier;
    }

    /**
     * Constructs a <code>IdentifyRequestParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentifyRequestParams} obj Optional instance to populate.
     * @return {module:model/IdentifyRequestParams} The populated <code>IdentifyRequestParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentifyRequestParams();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} identifier
 */
IdentifyRequestParams.prototype['identifier'] = undefined;






export default IdentifyRequestParams;

