/**
 * Dopt Users API
 * The Dopt Users API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentifySegmentRequestBody model module.
 * @module model/IdentifySegmentRequestBody
 * @version 0.0.0
 */
class IdentifySegmentRequestBody {
    /**
     * Constructs a new <code>IdentifySegmentRequestBody</code>.
     * @alias module:model/IdentifySegmentRequestBody
     * @param userId {String} 
     * @param traits {Object.<String, Object>} 
     */
    constructor(userId, traits) { 
        
        IdentifySegmentRequestBody.initialize(this, userId, traits);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, traits) { 
        obj['userId'] = userId;
        obj['traits'] = traits;
    }

    /**
     * Constructs a <code>IdentifySegmentRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentifySegmentRequestBody} obj Optional instance to populate.
     * @return {module:model/IdentifySegmentRequestBody} The populated <code>IdentifySegmentRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentifySegmentRequestBody();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('traits')) {
                obj['traits'] = ApiClient.convertToType(data['traits'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {String} userId
 */
IdentifySegmentRequestBody.prototype['userId'] = undefined;

/**
 * @member {Object.<String, Object>} traits
 */
IdentifySegmentRequestBody.prototype['traits'] = undefined;






export default IdentifySegmentRequestBody;

