/**
 * Dopt Users API
 * The Dopt Users API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InternalServerErrorResponseBodyCode model module.
 * @module model/InternalServerErrorResponseBodyCode
 * @version 0.0.0
 */
class InternalServerErrorResponseBodyCode {
    /**
     * Constructs a new <code>InternalServerErrorResponseBodyCode</code>.
     * @alias module:model/InternalServerErrorResponseBodyCode
     */
    constructor() { 
        
        InternalServerErrorResponseBodyCode.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InternalServerErrorResponseBodyCode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InternalServerErrorResponseBodyCode} obj Optional instance to populate.
     * @return {module:model/InternalServerErrorResponseBodyCode} The populated <code>InternalServerErrorResponseBodyCode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InternalServerErrorResponseBodyCode();

        }
        return obj;
    }


}






export default InternalServerErrorResponseBodyCode;

